---
title: 'Data Analysis 3: Week 8'
author: "Alexey Bessudnov"
date: "7 March 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(cache = TRUE)

```
Plan for today:

1. Assignment 3: solution.
2. Assignment 4.
3. Final statistical report.
4. Exercises: factors and other data types.
5. Homework for next week: control structures (if ... else) and iteration.


- Types of variables in social science research.

- R data structures.

- Vectors.

a) numeric (integer and double). Vectorisation.

Exercise 1. Create a vector of length 100, randomly drawing it from the standard normal distribution. Find the mean and standard deviation. Multiply the vector by 2. Are the meand and standard deviation going to change.

Exercise 2. Read the individual wave 8 UndSoc data and extract the variable for age from the data frame. What type if it?

b) logical.

Exercise 3. Convert sex into a logical vector for being male. Calculate the proportion of men in the data set.

c) character.

Exercise 4. Convert sex into a character vector with the values "male" and "female".

d) factors (augmented numeric).

Exercise 5. Convert sex into a factor. Change the order of levels.

Exercise 6. Split age into four categories (<30, 30-45, 46-60, >60), make it into a factor and set the levels in the correct order.

Exercise 7. Set "46-60" as the reference category.

Exercise 8. Produce a data frame with the mean earnings from main job by age group and reorder the levels for age according to mean earnings (in the decreasing order).

e) matrices and data frames.

f) lists.

Exercise 9. Make a list of four elements containing: 1) the vector from exercise 1, 2) the vector from exercise 3, 3) TRUE, 4) your name.

Exercise 10. Regress earnings on age and age squared. Extract regression coefficients as a vector.

g) missing values.

h) other data types: dates and times.








