---
title: 'Data Analysis 3: Week 9'
author: "Alexey Bessudnov"
date: "14 March 2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(cache = TRUE)

```
Plan for today:

1. Final statistical report.
2. Assignment 4: solutions.
3. Exercises on conditional statements and iteration.


Exercises.

1. Check if a number is even. If it is print "Even". If it isn't print "Odd". If it's 0 print "Zero".

2. Write a for loop finding the largest element of a numeric vector and print it on the screen.

3. Write a for loop finding the largest element of a numeric matrix and print it on the screen.

4. Write a while loop finding the largest element of a numeric vector and print it on the screen.

5. x is a vector with whole numbers (zero and positive integers).  If the largest even element of x is smaller than the largest odd element of x, all even elements of x are replaced by 0s. Otherwise all odd elements of x are replaced by 0s.

For example, if x = {7; 1; 3; 2; 14; 5; 9; 6} the output should be [0; 0; 0; 2; 14; 0; 0; 6].

6. x is a vector with whole numbers. Write a programme that count the number of pairs of the elements of x where the sum can be divided by 12 without a remainder.

For example, for x = {8; 10; 14; 7; 13; 5; 30; 9; 6} then the answer is 3 ((10, 14); (7, 5); (30, 6)).










